version: '3.8'

services:
  construct:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8100:8100"
    environment:
      - PORT=8100
      - DB_DRIVER=sqlite
      - DB_NAME=/data/construct.db
      - JWT_SECRET=${JWT_SECRET:-change-me-in-production}
      - CORS_ENABLED=false
    volumes:
      - construct-data:/data
      - construct-storage:/root/storage
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8100/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

  # Optional: PostgreSQL database
  # postgres:
  #   image: postgres:16-alpine
  #   environment:
  #     - POSTGRES_DB=construct
  #     - POSTGRES_USER=construct
  #     - POSTGRES_PASSWORD=${DB_PASSWORD:-change-me}
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   restart: unless-stopped

volumes:
  construct-data:
  construct-storage:
  # postgres-data: